### ISSUE TITLE
How do I pass a custom rules file to the GitHub action?

### ISSUE THREAD

**Issue by larseggert** [avto-dev/markdown-lint#11]
I tried pointing `rules:` at a rules file in the repository I want the action to run on, but that doesn't seem to work?

**Comment by tarampampam** [comment]
Can you provide more informtaion about error?

This config should work as you want:

```yaml
    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1
      with:
        rules: './your/rules.js'
        config: './your/config.yml'
        args: './path/to/the/target.md'
```

**Comment by larseggert** [comment]
My action is at https://github.com/NTAP/rfc8312bis/blob/markdownlint/.github/workflows/markdownlint.yml and has this bit:
```
      uses: docker://avtodev/markdown-lint:v1
      with:
        rules: './.markdownlint.json'
        args: 'draft-*.md'
```
My rules are at https://github.com/NTAP/rfc8312bis/blob/markdownlint/.markdownlint.json and contain:
```
{
  "default": true,
  "MD029": {"style": "ordered" },
  "MD034": false,
  "MD040": false,
  "MD041": false
}
```
The error is:
```
Error: Property 'names' of custom rule at index 0 is incorrect.
    at newError (/usr/local/bin/markdownlint:2:204300)
    at forProperty (/usr/local/bin/markdownlint:2:204531)
    at Array.forEach (<anonymous>)
    at forRule (/usr/local/bin/markdownlint:2:204391)
    at Array.forEach (<anonymous>)
    at validateRuleList (/usr/local/bin/markdownlint:2:204223)
    at lintInput (/usr/local/bin/markdownlint:2:212115)
    at Function.markdownlintSync [as sync] (/usr/local/bin/markdownlint:2:213059)
    at lintAndPrint (/usr/local/bin/markdownlint:2:4558)
    at Object.2390 (/usr/local/bin/markdownlint:2:4606)
```
