### ISSUE TITLE
Multiple files to ignore

### ISSUE THREAD

**Issue by ruzickap** [avto-dev/markdown-lint#7]
Hello.

Is there an easy way how to exclude multiple files form the linting process?

Something like:

```yaml
    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1
      with:
        ignore:
          - one_file.md
          - another_file.md
        args: '**.md'
```

^^^ This should recursively check all `*.md` files and skip two of them mentioned above.

Thank you
